all: except1 except2 except3 template1

except1: except1.cpp
	g++ -o $@ $<

except2: except2.cpp
	g++ -o $@ $<

except3: except3.cpp
	g++ -o $@ $<

template1: template1.cpp
	g++ -o $@ $<

clean:
	rm -f except?